package org.pytorch.helloworld;

public class DogCatClasses {
    public static String[] IMAGENET_CLASSES = new String[]{
            "American Pit Bull Terrier, 比特犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Great Pyrenees, 大白熊犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Havanese, 哈瓦那犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Chihuahua, 吉娃娃, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Pomeranian, 博美犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Scottish Terrier, 苏格兰梗犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Siamese, 暹罗猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Japanese Chin, 日本狆, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Samyoed, 萨摩耶犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Keeshond, 荷兰狮毛狗, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "American Bull dog, 美国斗牛犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Boxer, 拳师犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Wheaten Terrier, 爱尔兰软毛梗犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Sphynx, 斯芬克斯猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "English Cocker Spaniel, 英国可卡犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Persian, 波斯猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Main Coon, 缅因猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Staffordshire Bull Terrier, 史大丹佛郡斗牛梗, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "English Setter, 英国塞特犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Bombay, 孟买猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Leonberger, 兰伯格犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Shiba Inu, 柴犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Yorkshire Terrier, 约克郡梗, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Birman, 伯曼猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "British Shorthair, 英国短毛猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Russian Blue, 俄罗斯蓝猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Miniature Pinscher, 迷你杜宾犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Saint Bernard, 圣伯纳犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Beagle, 比格犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Egyptian Mau, 埃及猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "German Shorthaired, 德国短毛指示犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Ragdoll, 布偶猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Basset Hound, 巴吉度猎犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Bengal, 孟加拉猫, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Newfoundland, 纽芬兰犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Pug, 巴哥犬, 食物应以动物性蛋白为主，多喂饲高热量的食物",
            "Abyssinian, 阿比西尼亚猫, 食物应以动物性蛋白为主，多喂饲高热量的食物"
    };
}
